### ISSUE TITLE
Missing map.txt file

### ISSUE THREAD

**Issue by ghost** [Satomin2864/pyxel_pacomn#1]
Hello,

I get the following error.

```
$ python app.py
Traceback (most recent call last):
  File "app.py", line 318, in <module>
    App()
  File "app.py", line 55, in __init__
    self.reset()
  File "app.py", line 282, in reset
    self.map_load()
  File "app.py", line 286, in map_load
    load_file = open("map.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'map.txt'
```

**Comment by Satomin2864** [comment]
Hello, Marc-Alexandre Espiaut.
my project, I did not keep it up to date.
I made it the latest state. 
thank you！
